export function fixture(category = "parcel tracking software", count = 4, topicCount = 1, language = "en-US") {
  const source = { id: "owned", type: "owned_page", url: "https://client.example/products", title: category, snippet: `Current offering: ${category}. Buyers pay for this category. No unrelated products.`, publisher: "client.example" };
  const ext = { id: "external", type: "search_snippet", url: "https://review.example/article", title: category, snippet: `Buyers compare ${category} for price, fit and service.`, publisher: "review.example" };
  const market = { key: "primary", businessLine: category, canonicalL3Id: "", name: category, objectType: "software", definition: `Providers of ${category}`, exclusions: [], sourceIds: ["owned"], relation: "primary" };
  const business = { brandName: "Client Example", aliases: [], businessCategory: category, industryLabel: "测试行业", economicCenter: category, payingBuyer: "buyer", businessModel: "business", hypotheses: [{ interpretation: category, supportingSourceIds: ["owned"], conflictingSourceIds: [], unresolved: [] }], markets: [market], capabilities: [{ key: "cap", offering: category, buyer: "buyer", job: `choose ${category}`, outcome: "fit", constraints: [], marketKey: "primary", sourceIds: ["owned"], status: "confirmed" }], status: "confirmed", missingContext: [], researchQueries: [{ query: category, purpose: "category demand", marketKey: "primary" }], followupUrls: [], monitoringCountries: [{ country: "US", reason: "test market, not a traffic claim", sourceIds: ["owned"] }] };
  const surfaces = Array.from({ length: topicCount }, (_, n) => ({ key: `surface-${n}`, label: `${category} decision ${n}`, marketKey: "primary", buyer: "buyer", job: `choose ${category} ${n}`, decisionObject: `${category} ${n}`, criteria: ["fit"], sourceIds: ["owned", "external"], priority: "High" }));
  const units = Array.from({ length: count }, (_, n) => ({ key: `unit-${n}`, surfaceKey: surfaces[n % topicCount].key, marketKey: "primary", decisionObject: category, buyerContext: "buyer", job: `choose ${category}`, constraint: `test-distinct-requirement-${n}`, intent: "recommendation", subIntent: "scenario_fit", scope: "brand_core", benchmarkMember: true, pool: "monitoring_core", expectedEntityType: "brand_or_provider", capabilityKeys: ["cap"], sourceIds: ["owned", "external"], demandEvidence: "multiple_sources", demandReason: "Synthetic transport test, not real demand", journeyStage: "evaluate", priority: n % 2 ? "Medium" : "High", brandTermType: "generic", locationMode: "ip_only" }));
  const calls = [];
  const model = async ({ stage, payload }) => {
    calls.push(stage);
    if (stage.startsWith("business_")) return structuredClone(business);
    if (stage === "competitor_research") return { competitors: [], gaps: ["No verified provider page in synthetic fixture"] };
    if (stage === "decision_surfaces") return { surfaces: structuredClone(surfaces), exclusions: [], unresolved: [] };
    if (stage === "intent_enumeration") { const remaining = units.filter(u => payload.surfaces.some(s => s.key === u.surfaceKey) && !payload.existingUnits.some(e => e.key === u.key)); return { units: structuredClone(remaining.slice(0, 24)), exclusions: [], more: remaining.length > 24 }; }
    if (stage === "coverage_challenger") return { missingSurfaces: [], missingUnits: [], duplicateUnits: [], concerns: [] };
    if (stage === "topic_clustering") return { topics: surfaces.map(s => ({ key: s.key, name: s.label, marketKey: "primary", unitKeys: payload.units.filter(u => u.surfaceKey === s.key).map(u => u.key), decisionObject: s.decisionObject, job: s.job, rationale: "合并相同决策对象，保留独立需求。", priority: "High", type: "use_case" })).filter(t => t.unitKeys.length) };
    if (stage === "prompt_generation") return { prompts: payload.units.map(u => ({ unitKey: u.key, text: language === "zh-TW" ? `哪些${category}適合${u.constraint}？` : `Which ${category} supports ${u.constraint}?`, language, funnel: "MOFU", keywords: [category, u.constraint], contextAnchor: category })) };
    if (stage === "semantic_review") return { issues: [], checkedUnitKeys: payload.units.map(u => u.key) };
    throw new Error(`Unexpected model stage ${stage}`);
  };
  return { calls, model, business, units, deps: { model, modelId: "test/deterministic-fixture", network: { trace: [] }, crawl: async () => ({ sources: [source], pages: [{ url: source.url, title: category }], discoveredUrls: [source.url], attempted: [source.url], failures: [], remainingUrls: 0, remainingSitemaps: 0, families: ["offering"], budgetLimited: false }), search: async queries => ({ signals: [ext], log: queries.map(q => ({ query: q.query, resultCount: 1 })), remainingQueries: [] }), readPage: async () => { throw new Error("Synthetic fixture: no network"); } } };
}
